---
output: bookdown::gitbook
---
# Activity 1 - Exploring Categorical Data

## Tutorial Objective

The objective of this module is to equip you with the following:

- Use R/RStudio on a desktop/laptop to simulate confidence intervals for population parameters of interest.
- Construct plots and frequency tables for describing categorical data
- Assess association between variables

## Context of Data

The [**Survey of Consumer Finances** (SCF, 2013)](https://www23.statcan.gc.ca/imdb/p2SV.pl?Function=getSurvey&SDDS=3502) took a random sample of 6,015 adult Canadians and collected information on their level of education and whether or not they own a home. The variables "Education Level" and "Home Ownership" are measured as follows:

### Education Level
<ol style="margin-left: 20px;">
  <li>No High School Diploma</li>
  <li>High School Diploma or GED</li>
  <li>Some College</li>
  <li>College Degree</li>
</ol>

### Home Ownership
<ol style="margin-left: 20px;">
  <li>Yes (Owns House/Condo/Ranch/Farm/Mobile Home/etc.)</li>
  <li>No (Otherwise)</li>
</ol>

---

## R Setup

To set up and use R for this activity, follow the general instructions provided here:  
[**How to Access and Use R for Data Analysis Activities**](#how-to-set-up-r-for-data-analysis-activities).

Once you’ve set up your project and loaded the provided files, proceed with the activity-specific instructions below.

---

## Activity Instructions

1. Open the R script [`Home_SCF2013.R`](https://raw.githubusercontent.com/aslemand/Data-Analysis-Activities/main/data/Activity_1/Home_SCF2013.R) along with the data set [`Home_SCF2013.csv`](https://raw.githubusercontent.com/aslemand/Data-Analysis-Activities/main/data/Activity_1/Home_SCF2013.csv)  and run it line by line in RStudio.
2. Examine the data using the `str()` function to understand its structure and variable names.
3. Generate and interpret bar plots to visualize the relationship between education level and home ownership.
4. Modify the bar plot code (lines 124 to 143) to include your last name in the title:
   ```{r, eval = FALSE}
   library(ggplot2)
   
   # Exercise.
   # We will construct a side-by-side (clustered) bar chart of the data
   # bar.plot is a name where we want to save the plot and its features
   # ggplot function will make a canvas, 
   # and will make the plot ready using the data set and its variables of interest
   bar.plot = ggplot(Home2, aes(x = Education_Level, fill = Home_Ownership))
   # We will add the bars to the plot of the data
   # As well, we will add the legends and position it to the right-hand side
   bar.plot = bar.plot + geom_bar(position = "dodge")
   # We will add a label to the x-axis, 
   # We will differentiate the bars by filling in the levels of the response variable
   # We will add a title and a subtitle to the plot
   # And, we will centre the position of both the title and the subtitle
   # Modify line 140 with your last-name in the subtitle
   bar.plot = bar.plot + labs(xlab = "Education Level", fill = "Home Ownership",
                              title = "Bar Plot of Home Ownership and Education Level", 
                              subtitle = "Constructed by You")
   bar.plot = bar.plot + theme(plot.title=element_text(hjust=0.5), 
                               plot.subtitle = element_text(hjust=0.5))
   bar.plot
 
   ```
5. Save the modified bar plot as a `.jpeg` or `.png` file.
 
---

## Related Questions

1. Suppose we are interested in investigating the relationship between **home ownership** and **education level**:
   - Identify the response and explanatory variable.
   - Identify the role of each variable, their type, and their scale of measurement.

2. Find the marginal proportions of the response variable, convert them to percentages, and interpret.

3. Find the conditional proportions of the response variable for each category of the explanatory variable. Convert them to percentages and interpret.

4. Compute the difference between the proportion of homeownership for the "No High School Diploma" group and the "College Degree" group. Interpret this difference in context.

5. Compute the ratio between the proportion of homeownership for the "No High School Diploma" group and the "College Degree" group. Interpret this ratio in context.

6. Using data-based arguments (i.e., comparing conditional proportions), describe the relationship between the variables **"home ownership"** and **"education level"**.

---

## Submission Instructions

- Save your bar plot as a `.doc`, `.pdf`, `.jpeg`, or `.png` file.
- Provide your file to your instructor for feedback or assessment. 
