---
output: bookdown::gitbook
---
# Activity 5 - Estimation with Confidence Intervals

## Activity Objective

The objective of this module is to equip you with the following:
- Use R/RStudio on a desktop/laptop to simulate confidence intervals for population parameters of interest.
- Construct a confidence interval for one mean (known sigma) from a Normal Population.
- Construct a confidence interval for one mean (unknown sigma, small sample) from a Normal Population.
- Construct a confidence interval for one proportion.
- Construct a confidence interval for one variance.

---

## Context of Data

Suppose **STA123 course grades** are Normally distributed. Instead of collecting data from students, we will simulate (generate) some data for our example. To simulate data, we need to know the population mean and standard deviation of STA123 course grades. Here we assume the mean STA123 course grades is **70** and the standard deviation is **5**.

Using the sampled data, we obtain a **95% CI for population mean STA123 course grades**. Next, we carry out an experiment for CI interpretation. We know that a CI changes each time with a study. If we repeat the same study again and again, (1-\(\alpha\))% of the time the obtained confidence intervals would cover the true population parameter value. This can be shown through a simulation study or experiment. Using the STA123 course grades example, we can conduct an experiment using the following steps:

1. Generate a set of STA123 course grades data with 150 students from the population.
2. Calculate the observed sample mean of STA123 course grades and the standard error of \(\bar{X}\).
3. Calculate the confidence interval.
4. Check whether the confidence interval contains the population parameter value.
5. Repeat steps (1)-(4) **10,000 times** and count the total number of times that the confidence intervals contain the population value.
6. For a **95% CI**, one would expect about **9500 times** the CIs contain the population value.

Next, we draw a plot of the first 100 simulated confidence intervals and indicate those which do not contain the true population mean value of 70.

---

## Activity Instructions

1. Download the following file to your computer:
   - [R Script: Interval-Estimates-Simulations.R](https://raw.githubusercontent.com/aslemand/Data-Analysis-Activities/main/data/Activity_5/Interval-Estimates-Simulations.R)

2. Follow the instructions provided on the **How to Access and Use R for Data Analysis Activities** page to set up your R environment:  
   [**How to Access and Use R for Data Analysis Activities**](#how-to-set-up-r-for-data-analysis-activities).

3. Once you’ve set up your project folder and uploaded the file, proceed with the steps below:
   - Open the R script `Interval-Estimates-Simulations.R` and start running the provided code.

4. There are two required R code modifications:
   - **Line 15**: You need to input a seed number. Choose your seed number and put it into line 15 and run the line of code in R.
   - **Line 96**: You need to insert your last name in the title of the plot. Make the change to this line and upload your plot using this assignment page.

---

## Related Questions

Based on your R analysis (using your R outputs), answer the following related questions:

1. Refer to the plots of your sampled data (histogram, boxplot, and Normal QQ plot). Describe the distribution of sampled data.

2. Use the results of your sampled data to construct a **95% CI** for \( \mu \).  

3. Briefly describe the result of your simulation. What do you observe?

---

## Submission Instructions

Using this assignment page, upload your plot of the **95% confidence intervals** using your simulated data. The accepted file formats for Quercus submission are `.doc`, `.pdf`, `.jpeg`, or `.png` files.
